server:
  port: ${SERVER_PORT}

spring:
  application:
    name: ${SPRING_APPLICATION_NAME}

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER}

  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
    show-sql: ${SPRING_JPA_SHOW_SQL}
    defer-datasource-initialization: ${SPRING_JPA_DEFER_DATASOURCE_INIT}
    properties:
      hibernate:
        format_sql: ${SPRING_JPA_FORMAT_SQL}

  sql:
    init:
      mode: ${SPRING_SQL_INIT_MODE}
      continue-on-error: ${SPRING_SQL_INIT_CONTINUE_ON_ERROR}

logging:
  level:
    org.hibernate.SQL: ${LOGGING_LEVEL_HIBERNATE_SQL:DEBUG}
    org.hibernate.type.descriptor.sql.BasicBinder: ${LOGGING_LEVEL_HIBERNATE_BINDER:TRACE}
